### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by jojonarte** [isergey87/pjsip#1]
Yo how does this work?

I tried ./build_pjsip.sh

Then I get 

please input correct path to pjsip source as parameter 1

**Comment by isergey87** [comment]
`./build_pjsip.sh <path_to_pjsip> [<destination_path>]`
default destination path is build-ios/

you can run
`./build_pjsip.sh pjproject-2.4.5`

result will be in build-ios/

**Comment by jojonarte** [comment]
Hi I've tried it and have test on deploying to a real device why doesn't it work on an iPhone 6s with x86_64 architecture?
